# Source Plugin Configs
# ─────────────────────────

evaluate-commands %sh{
  for f in $(ls ${XDG_CONFIG_HOME}/kak/plugins)
  do
    echo "source ${XDG_CONFIG_HOME}/kak/plugins/$f"
  done
}



# Visual Options
# ─────────────────────────
set global ui_options ncurses_set_title=false
addhl global/ wrap
# Increase menu contrast
face global MenuBackground white,black
set global indentwidth 2

# Split Tmux 
# ─────────────────────────
define-command -params 0.. -file-completion \
  -docstring "split tmux pane vertically" split \
  %{ tmux-terminal-vertical kak -c %val{session} -e edit! %arg{@} }

define-command -params 0.. -file-completion \
  -docstring "split tmux pane horizontally" vsplit \
  %{ tmux-terminal-horizontal kak -c %val{session} -e edit! %arg{@} }

alias global sp split
alias global vs vsplit


# Default terminal
# ─────────────────────────
hook global ModuleLoaded "x11" %{
  set-option global termcmd "alacritty"
}


# System clipboard handling
# ─────────────────────────
hook global WinCreate .* %{ kakboard-enable  }


# Key Bindings
# ─────────────────────────

map global user d ':edit "%val{config}/../nixpkgs/home.nix"<ret>' -docstring 'edit kakrc'
map global user c ':comment-line <ret>' -docstring 'toggle line comments'
map global user f ':fzf-mode <ret>' -docstring 'fzf'


# Wants
# ─────────────────────────

# better markdown syntax highlighting (```{.python} should use python syntax highlighting )
# markdown send codeblock to repl
# tmux new vertical command
# fix or remove user mapped commands like surround and vertical select
# fix kak-explore
# make space in normalmode the user mode keybinding
# setup kak-connect better
# setup kak-lsp to be fast
# setup easy motion
# setup kak-gdb
# setup kak-sudo-write
