[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal", ".envrc", "shell.nix", "default.nix"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".ccls", ".git", ".envrc", "shell.nix", "default.nix"]
command = "ccls"
# Disable additional information in autocompletion menus that Kakoune inserts into the buffer until https://github.com/ul/kak-lsp/issues/40 gets fixed
args = ["--init={\"completion\":{\"detailedLabel\":false}}"]

[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg", ".envrc", "shell.nix", "default.nix"]
command = "pyls"

[language.markdown]
filetypes = ["markdown", "md"]
roots = [".git", ".envrc", "shell.nix", "default.nix", "flake.nix"]
command = "marksman"

[language.yaml]
filetypes = ["yaml", "yml"]
roots = [".git", ".envrc", "shell.nix", "default.nix", "flake.nix"]
command = "yaml-language-server"
args = ["--stdio"]

[language.nix]
filetypes = ["nix"]
roots = [".git", ".envrc", "shell.nix", "default.nix", "flake.nix"]
command = "nil"

[language.elixir]
filetypes = ["elixir"]
roots = [".git", "mix.exs", ".envrc", "shell.nix", "default.nix"]
command = "elixir-ls"

[language.php]
filetypes = ["php"]
roots = ["composer.json",".git", ".envrc", "shell.nix", "default.nix"]
command = "php-ls"


[language.ruby]
filetypes = ["ruby"]
roots = ["Gemfile", ".envrc", "shell.nix", "default.nix"]
command = "solargraph"
args = ["stdio"]

# -- UNUSED ---

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml", ".envrc", "shell.nix", "default.nix"]
command = "rls"

[language.javascript]
filetypes = ["javascript"]
roots = ["package.json", ".envrc", "shell.nix", "default.nix"]
command = "flow"
args = ["lsp"]

[language.json]
filetypes = ["json"]
roots = ["package.json", ".envrc", "shell.nix", "default.nix"]
command = "json-languageserver"
args = ["--stdio"]

[language.css]
filetypes = ["css"]
roots = ["package.json", ".envrc", "shell.nix", "default.nix"]
command = "css-languageserver"
args = ["--stdio"]

[language.html]
filetypes = ["html"]
roots = ["package.json", ".envrc", "shell.nix", "default.nix"]
command = "html-languageserver"
args = ["--stdio"]

[language.ocaml]
filetypes = ["ocaml"]
roots = ["Makefile", "opam", "*.opam", ".envrc", "shell.nix", "default.nix"]
command = "ocaml-language-server"
args = ["--stdio"]

[language.reason]
filetypes = ["reason"]
roots = ["package.json", "Makefile", ".git", ".hg", ".envrc", "shell.nix", "default.nix"]
command = "ocaml-language-server"
args = ["--stdio"]


[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg", ".envrc", "shell.nix", "default.nix"]
command = "go-langserver"
args = ["-mode", "stdio", "-gocodecompletion"]

[language.bash]
filetypes = ["sh"]
roots = [".git", ".hg", ".envrc", "shell.nix", "default.nix"]
command = "bash-language-server"
args = ["start"]

[language.dart]
filetypes = ["dart"]
roots = ["pubspec.yaml", ".git", ".envrc", "shell.nix", "default.nix"]
command = "dart_language_server"

[language.d]
filetypes = ["d", "di"]
roots = [".git", "dub.sdl", "dub.json", ".envrc", "shell.nix", "default.nix"]
command = "dls"
