# Source Plugin Configs
# ─────────────────────────

evaluate-commands %sh{
  for f in $(ls ${XDG_CONFIG_HOME}/kak/plugins)
  do
    echo "source ${XDG_CONFIG_HOME}/kak/plugins/$f"
  done
}

# Visual Options
# ─────────────────────────
set global ui_options ncurses_set_title=false
add-highlighter global/ number-lines -relative
addhl global/ wrap
# Increase menu contrast
face global MenuBackground white,black
set global indentwidth 2

# Default terminal
# ─────────────────────────
hook global ModuleLoaded "x11" %{
  set-option global termcmd "alacritty -e sh -c"
}


# System clipboard handling
# ─────────────────────────
hook global WinCreate .* %{ kakboard-enable }

# Key Bindings
# ─────────────────────────

map global user C ': comment-line <ret>' -docstring 'toggle line comments'

map global user c ': fzf-grep<ret>' -docstring 'fzf files by content'
map global user f ': fzf-files <ret>' -docstring 'fzf common files by name'
map global user b ': fzf-buffers <ret>' -docstring 'fzf buffers by name'
map global user h ': fzf-git-history<ret>' -docstring 'fzf git history'
map global user m ': make<ret>: buffer-previous<ret>' -docstring 'make'

map global user g ': connect terminal lazygit<ret>' -docstring 'lazygit'
map global user p ': connect terminal btop<ret>' -docstring 'btop'
map global user t ': connect terminal <ret>' -docstring 'terminal'

map global user | ': repl-new <ret>' -docstring 'create repl vertically inside tmux'
map global user s ': repl-send-text <ret>' -docstring 'send selection to repl'

map global user r ':rpueue status<ret>' -docstring 'view remote status'
map global user l ':rpueue log<ret>' -docstring 'view remote logs'

hook global WinSetOption filetype=(kak|markdown) %{
  map global user e ': eval %reg{.}<ret>' -docstring 'eval kakoune config selection'
  map global user i '<a-i>c```[^\n]*\n,```<ret>' -docstring 'select markdown code block'
  map global user v '<a-i>(:md-imv <ret>' -docstring 'open current markdown link with imv'
}


# Functions
# ─────────────────────────

define-command -docstring "cite using zotero, zotero needs to be open" zoterocite \
  %{
    set-register dquote %sh{
      curl -s "http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc&brackets=1"
    }
    execute-keys p
  }

define-command -docstring "evaluate selected kakoune script" do %{ eval %val{selection} }
