#!/usr/bin/env bash

# http://ryan.himmelwright.net/post/scripting-tmux-workspaces/

session=${PWD##*/}
kak -clear

tmux new-session -d -s $session

tmux rename-window -t 0 'Notes'
if [ -f notes.md ]; then
  tmux send-keys -t 'Notes' "kak -s $session notes.md" C-m
elif [ -f readme.md ]; then
  tmux send-keys -t 'Notes' "kak -s $session readme.md" C-m
else
  tmux send-keys -t 'Notes' "kak -s $session" C-m
fi

tmux new-window -t $session:1 -n 'Desktop'
tmux send-keys -t 'Desktop' "kak -c $session" C-m
tmux split-window -v -p 30
tmux attach-session -t $session:1
